name: signcentral
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # Pacotes necess√°rios:
  cupertino_icons: ^1.0.8
  google_sign_in: ^7.2.0
  flutter_svg: ^2.0.5
  url_launcher: ^6.3.0   # <--- AQUI, dentro de dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0   # <--- AQUI, dentro de dev_dependencies

flutter:
  uses-material-design: true

  assets:
    - assets/png/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_28pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_28pt-Bold.ttf
          weight: 700
